### ISSUE TITLE
karma-nightmare requires at least an empty options object

### ISSUE THREAD

**Issue by andregs** [bokuweb/karma-nightmare#4]
I want to launch Nightmare with default options, so I thought I could simply omit `nightmareOptions` in my config file. But I can't, because the following error is thrown:
```
[12:48:07] Starting 'test'...
27 01 2017 12:48:31.333:INFO [karma]: Karma v1.2.0 server started at http://localhost:9876/
27 01 2017 12:48:31.333:INFO [launcher]: Launching browser Nightmare with unlimited concurrency
27 01 2017 12:48:31.333:INFO [launcher]: Starting browser Nightmare
undefined:1
undefined
^

SyntaxError: Unexpected token u
    at Object.parse (native)
    at Object.<anonymous> (C:\Users\myself\workspace\myproject\node_modules\karma-nightmare\lib\browser.js:3:22)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3

27 01 2017 12:48:31.599:ERROR [launcher]: Cannot start Nightmare
```

The workaround is to provide at least `nightmareOptions: {}`.

**Comment by andregs** [comment]
Sorry, already fixed: #1
